# Cloud Build configuration for automatic deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE_NAME:$COMMIT_SHA', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE_NAME:$COMMIT_SHA']

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '$_MEMORY'
      - '--cpu'
      - '$_CPU'
      - '--max-instances'
      - '$_MAX_INSTANCES'
      - '--min-instances'
      - '$_MIN_INSTANCES'

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'housing-price-predictor'
  _IMAGE_NAME: 'housing-price-predictor'
  _MEMORY: '1Gi'
  _CPU: '1'
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '0'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
